### ISSUE TITLE
Streaming API Silent Disconnect

### ISSUE THREAD

**Issue by zrc210** [ejholmes/restforce#318]
I am currently in the process of debugging a silent disconnect between the streaming API and salesforce.

Unfortunately, the problem is difficult to reproduce on a small time scale - the latest disconnect has happened after almost 12 days of uninterrupted messages being passed from Salesforce. Restarting the script instantly restores the connection, and messages are received once again.

I have Info Level logs enabled on Restforce, however, they do not capture anything of interest, and no error logs at all. Even after the ruby process has stopped receiving updates, the ruby process is still running, and still has an `ESTABLISHED` TCP connection to salesforce.

I am running Ruby 2.4.1, restforce 2.5.3, and faye 0.8.9.

What can I enable in terms of logging to aid in tracing the root cause of this?

I have a strong suspicion that this is an issue with faye that has likely been resolved since 0.8.9 - but https://github.com/ejholmes/restforce/issues/114 is still open, without any commits or PR's posted against it.

Is there work, active, planned, or abandoned that is making restforce compatible with versions of the faye gem greater than 0.8.9? Even if it is abandoned, I'd be interested to see what progress has been made, and see what else needs to be done.

Apologies in advance if this is a duplicate, however, I attempted to look through the existing open issues on restforce, but nothing seems to be similar to this issue. Has anyone else seen something like this?

**Comment by timrogers** [comment]
I'm afraid that despite being the maintainer, I'm not familiar with the streaming side having never had cause to use it myself. It might be worth tagging in some people who've got involved in other streaming issues? (e.g. #265)

**Comment by zrc210** [comment]
Ok, Upgrading the Latest version of Restforce and Faye seems to work sometimes.
However, there is an unhanded exception being raised:

```
<KeyError: key not found: "channel">

```
"gems/restforce-3.1.0/lib/restforce/concerns/streaming.rb:52:in `fetch'",
"gems/restforce-3.1.0/lib/restforce/concerns/streaming.rb:52:in `block in incoming'",
"gems/restforce-3.1.0/lib/restforce/concerns/streaming.rb:51:in `tap'",
"gems/restforce-3.1.0/lib/restforce/concerns/streaming.rb:51:in `incoming'",
"gems/faye-1.2.4/lib/faye/protocol/extensible.rb:38:in `block in pipe_through_extensions'",
"gems/faye-1.2.4/lib/faye/protocol/extensible.rb:41:in `pipe_through_extensions'",
"gems/faye-1.2.4/lib/faye/protocol/client.rb:312:in `receive_message'",
"gems/websocket-driver-0.7.0/lib/websocket/driver/event_emitter.rb:39:in `block in emit'",
"gems/websocket-driver-0.7.0/lib/websocket/driver/event_emitter.rb:38:in `each'",
"gems/websocket-driver-0.7.0/lib/websocket/driver/event_emitter.rb:38:in `emit'",
"gems/faye-1.2.4/lib/faye/protocol/dispatcher.rb:133:in `handle_response'",
"gems/faye-1.2.4/lib/faye/transport/transport.rb:106:in `block in receive'",
"gems/faye-1.2.4/lib/faye/transport/transport.rb:105:in `each'",
"gems/faye-1.2.4/lib/faye/transport/transport.rb:105:in `receive'",
"gems/faye-1.2.4/lib/faye/transport/http.rb:76:in `handle_response'",
"gems/faye-1.2.4/lib/faye/transport/http.rb:18:in `block in request'"
```

I'm going to enable debug logging on the Faye Gem to see if we can capture anything obvious.

**Comment by rywall** [comment]
@zrc210 I'm also seeing this `key not found` issue after upgrading Restforce to 3.1.0. Did you manage to figure anything out regarding this error?

**Comment by rywall** [comment]
I fixed this particular error (`key not found: "channel"`) in my app by locking faye to `0.8.9` (while leaving restforce at `3.1.0`).

With a newer version of faye (`1.2.4`) I get the following `message` passed to https://github.com/restforce/restforce/blob/8744f3c4d2461e7eaf9f7d0f6963c2ce6b0ab33f/lib/restforce/concerns/streaming.rb#L50.

`{"clientId"=>"4f1mmkodgnsirk815i198g266ikp", "error"=>"403::Unknown client", "successful"=>false}`

This seems to suggest that the connection was unsuccessful, I guess due to incompatibilities with newer versions of faye, though I didn't investigate exhaustively.

**Comment by zrc210** [comment]
@rywall - I'm still having issues, but haven't had the chance to debug too deeply. I stopped getting that key not found error after upgrading to the latest version of the salesforce API. ApiVersion: 43.0 or so. The default version used by restforce is super old - https://github.com/restforce/restforce#api-versions. I wonder if the Salesforce API version is relevant to channel issue...

**Comment by zrc210** [comment]
@rywall Ok, Enabling debugging does reveal some things to investigate further:
```
The replayId for channel {/topic/<redacted>} wasn't found using the provided replay ID map {{/topic/<redacted>=null}}. Ensure that the channel name you provided in the replay map is valid and matches the channel name used for subscribing
```

I wonder if we need to send the magic value of `-1` as per [the documentation](https://github.com/restforce/restforce/commit/d8dd602d24f7ec627c83baa2b9677d40c0edc46d)

However, unrelated to that, I am getting the 403::Unknown Client error as well. Searching for `advice":{"interval":0,"reconnect":"handshake"` does bring up this interesting post: https://github.com/kevinohara80/nforce/issues/131

@yaronyagoda had mentioned in https://github.com/restforce/restforce/pull/265#issuecomment-320035474 that he had found a solution to the silent disconnect. Looking over some of the forked branches - https://github.com/yaronyagoda/restforce/commit/4af6e94b3f549c2d6ef0bb5e59bcfb34032ac453 seems to "catch" the disconnect.

@yaronyagoda - any chance you've been able to test that solution with the latest versions of faye and restforce? If so, would you be able to create PR for us to evaluate?

**Comment by KuhlTime** [comment]
@zrc210 I am having the same issue, did you find any solution to this problem?

**Comment by zrc210** [comment]
@KuhlTime unfortunately, I'm no longer involved with the project that was using this solution, and haven't been for some time (nearly 4 years). When I last looked at this, we worked around the issue by having a cron periodically restart the syncing service. We monitored after how many hours we would see the disconnect on average, and configured the restart at an interval around the same time frame.

While not ideal, it reduced our support burden significantly, and it automated the recovery, so if syncing did break, it would eventually heal.

Sorry for not having a better answer for you.

**Comment by KuhlTime** [comment]
Hi @zrc210 thanks for your response 🫶. Will have another look at what can be done and then decide whether I will do a cron job as well.
